services:
  productservice:
    build: product-service
    ports:
      - "5000:5000"
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
