services:
  productservice:
    build: product-service
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://root:${MYSQL_ROOT_PASSWORD}@db/products

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mysql
    command: "--init-file /data/application/init.sql"
    volumes:
      - "./db/init.sql:/data/application/init.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file:
      - ./product-service/src/.env 
