CREATE DATABASE IF NOT EXISTS products;

USE products;

CREATE TABLE IF NOT EXISTS products (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (128) NOT NULL
)  ENGINE=INNODB;

INSERT INTO products (name) VALUES ('Product 1'), ('Product 2');